### DISCUSSION TITLE
I'm running monica on docker how can I enable multiple account registrations ?

### DISCUSSION THREAD

**Discussion by MichaelData** [monicahq/monica#5630] [Q&A]
Hello everyone. It took hours to get monica CRM to work on docker now that I've got it working I wanted to let my friends sign up on it also on my server. how can do that ?

Here is docker-compose script I have

I'm still learning docker scripting so I hope you don't mind if I ask a lot of questions. 

```
version: "3.8"

services:
  app:
    image: monica
    depends_on:
      - db
    ports:
      - 8485:80
    environment:
      - DB_HOST=db
      - DB_CONNECTION=mysql
      - DB_PORT=3306
      - DB_DATABASE=monica
      - DB_USERNAME=homestead
      - DB_PASSWORD=changeme
    restart: always
    networks:
      - db_net

  db:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=changeme
    volumes:
      - db_volume:/var/lib/mysql
    restart: always
    networks:
      - db_net
networks:
  db_net:

volumes:
  db_volume:
```
