### DISCUSSION TITLE
First time setup: Monica or Chandler?

### DISCUSSION THREAD

**Discussion by slifty** [monicahq/monica#6904] [Q&A] [answered]
I finally got MonicaHQ set up on my home server!... and then see that Chandler is the future.

Does anybody have advice on whether it would make more sense for me to just set up Chandler (since I have no data) or should I stick with Monica and wait for the formal collective migration to the new tool.

**Comment by djaiss** [comment, marked as answer]
I would suggest that you use Chandler instead. No work will be done on Monica from now on.

**Reply by slifty** [reply]
Thank you!  Now I'm off to figure out the best way to do that installation.

My setup is using FPM, since the apache docker layer used by this project breaks on my NAS's old kernel.  I assume there is no equivalent FPM image for chandler just yet; I also assume you don't want to publish one until Chandler's out of beta, so I'll make the image myself for now!

**Comment by JakubJeziorski** [comment]
I am a bit lost, how do I use chandler if it is marked as read only? How do I install it on docker?

**Reply by cellulosa** [reply]
Hi @JakubJeziorski, you can run the one-liner provided by [the guide](https://docs.monicahq.com/developers/docker), but I prefer to use docker-compose (snippet below).

Either way remember to set the sqlite file somewhere on your drive so that the data will be saved even if you destroy and re-create the docker container:

```
monica:
  container_name: monica
  image: ghcr.io/monicahq/monica-next:main
  ports:
    - 8080:80
  environment:
    - DB_DATABASE=/var/www/html/storage/database.sqlite
    - MAIL_MAILER=log
  volumes:
    - ~/monica/database.sqlite:/var/www/html/storage/database.sqlite
  restart: unless-stopped
```

You can also set all sorts of other variables depending on your needs e.g.

```
  - APP_URL=
  - APP_TRUSTED_PROXIES=
  - APP_KEY=
  - DB_PASSWORD=
  - MAIL_MAILER=
  - MAIL_HOST=
  - MAIL_PORT=
  - MAIL_USERNAME=
  - MAIL_PASSWORD=
  - MAIL_ENCRYPTION=
  - MAIL_FROM_ADDRESS=
  - LOCATION_IQ_API_KEY=
  - MAPBOX_API_KEY=
  - MAPBOX_USERNAME=
  - UPLOADCARE_PUBLIC_KEY=
  - UPLOADCARE_PRIVATE_KEY=
 ```
