### DISCUSSION TITLE
Account Verification with Mail Logger Not Working

### DISCUSSION THREAD

**Discussion by jrpetersjr** [monicahq/monica#7147] [Q&A]
Hello,

I setup Monica (chandler Beta) and I when though the signup process with the MAIL_MAILER=log and I can't find the log file where the verification email is being sent to. When I look at /mnt/raid1/dockerdata/monica/logs there's nothing in there so I am unable to verify. TIA for any help

```yaml
version: '3.4'
services:
  monica:
    container_name: monica
    image: ghcr.io/monicahq/monica-next:main
    ports:
      - 3001:80
    environment:
      - MAIL_MAILER=log
    volumes:
      - /mnt/raid1/dockerdata/monica:/var/www/html/storage
    restart: unless-stopped
```

<img width="710" alt="image" src="https://github.com/monicahq/monica/assets/9285616/d558228a-ac43-4dc1-88a5-b97390c2200b">
