### DISCUSSION TITLE
Micrating from sqlite to postgres

### DISCUSSION THREAD

**Discussion by cellulosa** [monicahq/monica#7153] [Show and tell]
Today I migrated from sqlite to postgres to be able to get the meilisearch search working on chandler ([discussion](https://github.com/monicahq/monica/discussions/6904#discussioncomment-8428483)). I thought maybe this could be of use to somebody else, so there you go. I am be using `docker-compose` and env variables to make it obvious where things ought to be personalised.

1. Spin up a postgres instance

```yml
  monica-postgres:
    container_name: monica-postgres
    image: postgres:alpine
    volumes:
      - ${DOCKER_CONFIG_DIR}/monica/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=monica
      - POSTGRES_DB=monica
      - POSTGRES_PASSWORD=${MONICA_POSTGRES_PASS}
    ports:
      - 5432:5432
```

2. install [pgloader](https://github.com/dimitri/pgloader) (on mac with `brew install pgloader`) and create the following file (named `pgloader-migration.load`):

```yml
load database
    from sqlite://${DOCKER_CONFIG_DIR}/monica/database.sqlite
    into postgres://monica:${MONICA_POSTGRES_PASS}@localhost:5432/monica

with include drop, create tables, create indexes, reset sequences, concurrency = 1, workers=2

set work_mem to '16MB', maintenance_work_mem to '512 MB';
```

3. Run Monica with postrgres and let it create the database as if it was a fresh new install:

```yml
  monica:
    container_name: monica
    image: ghcr.io/monicahq/monica-next:main
    # volumes: # no need for this anymore
      # - ${DOCKER_CONFIG_DIR}/monica/database.sqlite:/var/www/html/storage/database.sqlite
    environment:
      (...)
      # - DB_DATABASE=/var/www/html/storage/database.sqlite # we're switching to postgres
      - DB_CONNECTION=pgsql
      - DB_HOST=monica-postgres
      - DB_PORT=5432
      - DB_DATABASE=monica
      - DB_USERNAME=monica
      - DB_PASSWORD=${MONICA_POSTGRES_PASS}
```

5. Now you can run the migration with `pgloader pgloader-migration.load`. Hopefully you'll see no errors 🤞 

6. Now you can remove the `ports` section of the postgres instance, as monica will be able to communicate with it internally.

If you want to make the search work, you either run `docker exec monica php artisan queue:listen --queue=high,low,default` [as per docs](https://docs.monicahq.com/developers/setup-local-development), or spin a redis instance to manage the queue (what I did). Obiously you also need a meilisearch instance.

Here's my full `docker-compose` in case you're interested:

```yml
  monica:
    container_name: monica
    image: ghcr.io/monicahq/monica-next:main
    environment:
      - APP_ENV=production
      - APP_URL=https://monica.${MY_DOMAIN}
      - APP_TRUSTED_PROXIES=*
      - APP_KEY=${MONICA_APP_KEY}
      - DB_CONNECTION=pgsql
      - DB_HOST=monica-postgres
      - DB_PORT=5432
      - DB_DATABASE=monica
      - DB_USERNAME=monica
      - DB_PASSWORD=${MONICA_POSTGRES_PASS}
      - MAIL_MAILER=log
      - LOCATION_IQ_API_KEY=${MONICA_LOCATION_IQ_API_KEY}
      - MAPBOX_API_KEY=${MONICA_MAPBOX_API_KEY}
      - MAPBOX_USERNAME=${MAPBOX_USERNAME}
      - UPLOADCARE_PUBLIC_KEY=${MONICA_UPLOADCARE_PUBLIC_KEY}
      - UPLOADCARE_PRIVATE_KEY=${MONICA_UPLOADCARE_PRIVATE_KEY}
      - MEILISEARCH_HOST=http://monica-meilisearch:7700
      - MEILISEARCH_KEY=${MONICA_MEILI_MASTER_KEY}
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=monica-redis
      - REDIS_PASSWORD=${MONICA_REDIS_PASSWORD}
    depends_on:
      - monica-postgres
      - monica-meilisearch
      - monica-redis
    networks:
      - frontend
      - backend

  monica-postgres:
    container_name: monica-postgres
    image: postgres:alpine
    volumes:
      - ${DOCKER_CONFIG_DIR}/monica/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=monica
      - POSTGRES_DB=monica
      - POSTGRES_PASSWORD=${MONICA_POSTGRES_PASS}
    networks:
      - backend

  monica-meilisearch:
    container_name: monica-meilisearch
    image: getmeili/meilisearch:latest
    volumes:
      - ${DOCKER_CONFIG_DIR}/monica/meilisearch:/meili_data
    environment:
      - MEILI_MASTER_KEY=${MONICA_MEILI_MASTER_KEY} # https://www.meilisearch.com/docs/learn/security/master_api_keys
    networks:
      - backend

  monica-redis:
    container_name: monica-redis
    image: redis:alpine
    volumes:
      - ${DOCKER_CONFIG_DIR}/monica/redis:/data
    command: /bin/sh -c "redis-server --requirepass ${MONICA_REDIS_PASSWORD}"
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
```
