### DISCUSSION TITLE
v5 beta throws `Cannot read properties of null (reading 'refs')`

### DISCUSSION THREAD

**Discussion by KaKi87** [monicahq/monica#7279] [Q&A]
Hi,

Here's my `compose.yml` :

```yml
services:
  app:
    image: monica:5.0.0-beta.4-apache
    env_file: .env
    depends_on:
      - db
    ports:
      - 1234:80
    volumes:
      - data:/var/www/html/storage
    restart: always

  cron:
    image: monica
    env_file: .env
    restart: always
    volumes:
      - data:/var/www/html/storage
    command: cron.sh
    depends_on:
      - db

  db:
    image: mariadb:11
    env_file: .env
    volumes:
      - mysql:/var/lib/mysql
    restart: always

volumes:
  data:
    name: data
  mysql:
    name: mysql
```

And here's my Apache configuration :

```
<VirtualHost *:80>
    ServerName example.com
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
</VirtualHost>

<VirtualHost *:443>
    ServerName example.com
    ProxyRequests Off
    ProxyPass / http://localhost:1234/
    ProxyPassReverse / http://localhost:1234/
    Header always set Content-Security-Policy "upgrade-insecure-requests"
    SSLCertificateFile /home/example/.acme.sh/example.com_ecc/fullchain.cer
    SSLCertificateKeyFile /home/example/.acme.sh/example.com_ecc/example.com.key
</VirtualHost>
```

When browsing to the frontend, I get redirected to `/login`, but then I'm encountering an empty blue page with throwing the following error in console :

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'refs')
    at Xl (VM1367 app-CH3t7HKu.js:50:33434)
    at w (VM1367 app-CH3t7HKu.js:50:38376)
    at W (VM1367 app-CH3t7HKu.js:50:39795)
    at N (VM1367 app-CH3t7HKu.js:50:39081)
    at k (VM1367 app-CH3t7HKu.js:50:38882)
    at w (VM1367 app-CH3t7HKu.js:50:38254)
    at W (VM1367 app-CH3t7HKu.js:50:39795)
    at N (VM1367 app-CH3t7HKu.js:50:39081)
    at k (VM1367 app-CH3t7HKu.js:50:38882)
    at w (VM1367 app-CH3t7HKu.js:50:38254)
```

What to do ?

Thanks
