### DISCUSSION TITLE
503 Service Temporarily Unavailable

### DISCUSSION THREAD

**Discussion by J0han3s** [monicahq/monica#7403] [Q&A]
Hi 

I am trying to set up Monica, after several hours, i think i am very close. as each service/container in docker seems to be in a healthy state now. however, i cannot access Monica.  I followed the example from [here for ssl ](https://github.com/monicahq/docker/tree/main/.examples/nginx-proxy-self-signed-ssl).

**problem**
when i go to monica_ip_address:80 i get "503 Service Temporarily Unavailable". 
when i go to monica_ip_address:443, i gett "Hmmm… can't reach this page [monica_ip_address] refused to connect."

dockerfile
```


services:
  app:
    image: local/monica_app:custom
    env_file: stack.env
    volumes:
      - /mnt/Monica/data:/var/www/html/storage
    restart: always
    
    depends_on:
      - db
      - redis
     
  db:
    image: mariadb:11
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret

    volumes:
      - /mnt/Monica/db:/var/lib/mysql
    restart: always

  redis:
    image: redis:alpine
    restart: always

  cron:
    image: local/monica_app:custom
    command: cron.sh
    env_file: stack.env
    restart: always
    volumes:
      - /mnt/Monica/data:/var/www/html/storage
    depends_on:
      - db
      - redis

  queue:
    image: local/monica_app:custom
    command: queue.sh
    env_file: stack.env
    restart: always
    volumes:
      - /mnt/Monica/data:/var/www/html/storage
    depends_on:
      - db
      - redis

  web:
    image: local/monica_web:custom
    restart: always
    environment:
      - VIRTUAL_HOST=monica.domain.com
    volumes:
      - /mnt/Monica/data:/var/www/html/storage:ro
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  proxy:
    image: local/monica_proxy:custom	
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /mnt/Monica/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - omgwtfssl

  omgwtfssl:
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - /mnt/Monica/certs:/certs
    environment:
      - SSL_SUBJECT=monica.domain.com
      - CA_SUBJECT=bob@yahoo.nl
      - SSL_KEY=/certs/monica.domain.com.key
      - SSL_CSR=/certs/monica.domain.com.csr
      - SSL_CERT=/certs/monica.domain.com.crt
    networks:
      - proxy-tier

networks:
  proxy-tier:`



```

monica applogs
```

Database ready.[10-Oct-2024 23:26:32] NOTICE: fpm is running, pid 1
NOTICE: ready to handle connections

```

db logs
```

2024-10-10 23:26:44 0 [Note] mariadbd: Event Scheduler: Loaded 0 events

2024-10-10 23:26:44 0 [Note] mariadbd: ready for connections.

Version: '11.5.2-MariaDB-ubu2404'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary

```

web logs

```

/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up

```

proxy logs

(Info: running nginx-proxy version 1.6.2
Warning: A custom dhparam.pem file was provided. Best practice is to use standardized RFC7919 DHE groups instead.
Warning: TRUST_DOWNSTREAM_PROXY is not set; defaulting to "true". For security, you should explicitly set TRUST_DOWNSTREAM_PROXY to "false" if there is not a trusted reverse proxy in front of this proxy.
Warning: The default value of TRUST_DOWNSTREAM_PROXY might change to "false" in a future version of nginx-proxy. If you require TRUST_DOWNSTREAM_PROXY to be enabled, explicitly set it to "true".
forego      | starting dockergen.1 on port 5000
forego      | starting nginx.1 on port 5100
nginx.1     | 2024/10/10 23:26:31 [notice] 17#17: using the "epoll" event method
nginx.1     | 2024/10/10 23:26:31 [notice] 17#17: nginx/1.27.2
nginx.1     | 2024/10/10 23:26:31 [notice] 17#17: built by gcc 13.2.1 20240309 (Alpine 13.2.1_git20240309) 
nginx.1     | 2024/10/10 23:26:31 [notice] 17#17: OS: Linux 6.8.12-1-pve
nginx.1     | 2024/10/10 23:26:31 [notice] 17#17: getrlimit(RLIMIT_NOFILE): 524288:524288
nginx.1     | 2024/10/10 23:26:31 [notice] 17#17: start worker processes
nginx.1     | 2024/10/10 23:26:31 [notice] 17#17: start worker process 18
nginx.1     | 2024/10/10 23:26:31 [notice] 17#17: start worker process 19
dockergen.1 | 2024/10/10 23:26:32 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2024/10/10 23:26:32 Watching docker events
dockergen.1 | 2024/10/10 23:26:32 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2024/10/10 23:26:32 Received event stop for container acb596d6b2b6
dockergen.1 | 2024/10/10 23:26:32 Received event die for container acb596d6b2b6
dockergen.1 | 2024/10/10 23:26:33 Received event start for container acb596d6b2b6
dockergen.1 | 2024/10/10 23:26:33 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2024/10/10 23:26:34 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2024/10/10 23:26:34 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2024/10/10 23:26:36 Received event stop for container 9e9df83656e2
dockergen.1 | 2024/10/10 23:26:36 Received event die for container 9e9df83656e2
dockergen.1 | 2024/10/10 23:26:38 Received event start for container 9e9df83656e2
dockergen.1 | 2024/10/10 23:26:38 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2024/10/10 23:26:38 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2024/10/10 23:26:38 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2024/10/10 23:26:42 Received event die for container ba602c642ab3
dockergen.1 | 2024/10/10 23:26:43 Received event start for container f579f5391712
dockergen.1 | 2024/10/10 23:26:44 Received event start for container ba602c642ab3
dockergen.1 | 2024/10/10 23:26:44 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2024/10/10 23:26:44 Received event die for container f579f5391712
dockergen.1 | 2024/10/10 23:26:44 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2024/10/10 23:26:44 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2024/10/10 23:26:44 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx.1     | [monica_ip] [my laptop ip]- - [10/Oct/2024:23:28:30 +0000] "GET /favicon.ico HTTP/1.1" 400 650 "http://[monica_ip]:443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0" "-"

queue logs

```

In Connection.php line 760:
                                                                               
  SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `cache` where  
   `key` = laravel_cacheilluminate:queue:restart limit 1)                      
                                                                               
In Connector.php line 70:
                                             
  SQLSTATE[HY000] [2002] Connection refused  
                                             
```

redis logs

```

1:M 10 Oct 2024 23:26:34.064 * DB loaded from disk: 0.000 seconds
1:M 10 Oct 2024 23:26:34.064 * Ready to accept connections tcp


```
