### DISCUSSION TITLE
New installation of Chandler uses Sqlite even though MySQL provided

### DISCUSSION THREAD

**Discussion by Royal2000H** [monicahq/monica#7716] [Q&A]
Trying to set up a new installation (v5 beta) on Synology.

Have the following Docker Compose:

```
services:
  app:
    image: monica:5.0-apache
    container_name: monica
    depends_on:
      - db
    ports:
      - 1994:80
    environment:
      - APP_KEY=<secret1>
      - DB_HOST=db
      - DB_USERNAME=monica
      - DB_PASSWORD=<secret2>
    volumes:
      - /volume1/docker/monica/data:/var/www/html/storage
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  db:
    image: mariadb:11
    container_name: monica-db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=<secret2>
    volumes:
      - /volume1/docker/monica/mysql:/var/lib/mysql
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
```

Despite this, when starting the container for the first time, logs show it's starting a sqlite DB because there's no MySQL/MariaDB. Yet there is, as seen above.

Also despite having the volumes referenced and the apps creating files and folders within the referenced folders (/volume1/docker/monica/data and /volume1/docker/monica/mysql), the DB itself isn't persistent and if I clean a re-build the image, the DB is reset.

Any advice?
