### ISSUE TITLE
Docker image for raspberry

### ISSUE THREAD

**Issue by mNantern** [monicahq/monica#1528]
I want to be able to run Monica on my Raspberry PI.

I made it work by building a new Docker image (following the blog post: https://blog.hypriot.com/post/setup-simple-ci-pipeline-for-arm-images/) for Monica and replacing the official mysql image by `hypriot/rpi-mysql`.

Please find below my docker-compose:

```
version: "2"
services:
  monicahq:
    build: .
    image: mnantern/rpi-monicahq
    links:
      - mysql
    ports:
      - 3000:80
    env_file: .env
    volumes:
      - ./data/monica:/var/www/monica/storage/app/public

  mysql:
    image: hypriot/rpi-mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=xxxx
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=xxxx
    volumes:
      - ./data/mysql:/var/lib/mysql
```

Are you interested in a PR ?
