### ISSUE TITLE
Using an SMTP container to send E-mail notifications

### ISSUE THREAD

**Issue by cristobaltapia** [monicahq/monica#1913]
Hi, first I wanted to thank you for this project. It is very good! :)

I have been playing with the docker version of it for the last two days but there is one thing that I still cannot get to work correctly: Email notifications.

I have created an SMTP service in the `docker-compose.yml` file, but it seems to not be working (I have tested the docker independently and it does send Emails: [namshi/docker-smtp
](https://github.com/namshi/docker-smtp)).

This what I have done:
`docker-compose.yml`
```yml
version: "2"
services:
  monicahq:
    image: monicahq/monicahq
    links:
      - mysql
    ports:
      - 3000:80
    env_file: .env
    volumes:
      - ./data/storage:/var/www/monica/storage

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=xxxxx
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=xxxxx
    volumes:
      - ./data/mysql:/var/lib/mysql

  mail:
    image: namshi/smtp
    restart: always
    ports:
      - "25:25"

```

and in the `.env` file I have edited the Email variables like this:

```sh
MAIL_DRIVER=smtp
MAIL_HOST=mail
MAIL_PORT=25
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=
MAIL_FROM_ADDRESS=some@email.com
MAIL_FROM_NAME="Server: Monica"
```
Any idea of what might be wrong?
