### ISSUE TITLE
MonicaHQ behind reverse proxy (jwilder image for example)

### ISSUE THREAD

**Issue by reyman** [monicahq/monica#1931]
Hi,

I'm trying to use monicaHQ behind a reverse proxy, without success, it could be a good idea to had this possibility.

The jwilder/nginx-proxy great docker image use two env variable to generate a new `/etc/nginx/conf.d/defaut.conf`

It works very well with other project, but not without MonicaHQ, 

My dockerfile : 

```
version: "3"
services:
  monicahq:
    build: .
    image: monicahq/monicahq
    networks:
      backend:
    links:
      - mysql
    ports:
      - 3500:3500
    environment:
      - VIRTUAL_HOST=reseau.sebastienreycoyrehourcq.fr
      - VIRTUAL_PORT=3500
    env_file: .env
    volumes:
      - /home/reyman/Volumes/monica/:/var/www/monica/storage

  mysql:
    image: mysql:5.7
    networks:
      backend:
    environment:
      - MYSQL_ROOT_PASSWORD=xxx
      - MYSQL_DATABASE=monica
      - MYSQL_USER=reyman
      - MYSQL_PASSWORD=xxx
    volumes:
      - /home/reyman/Volumes/mysqlMonica:/var/lib/mysql

# Define networks to allow best isolation
networks:
  # Internal network for communication with PostgreSQL/MySQL
  backend:
```

My env file, i copy/paste only the modified values ! 
```

APP_ENV=production
APP_DEBUG=true
APP_KEY=xxxxxxxxxxxxxxxxxxxxxxxxx
HASH_SALT=xxxxxxxxxxxxxxxxxxxx
HASH_LENGTH=20
APP_URL=http://reseau.sebastienreycoyrehourcq.fr
DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=monica
DB_USERNAME=reyman
DB_PASSWORD=xxxx
DB_PREFIX=
DB_TEST_HOST=127.0.0.1
DB_TEST_DATABASE=monica_test
DB_TEST_USERNAME=reyman
DB_TEST_PASSWORD=xxxx
```

The part of default.conf generated by jwilder/nginx-proxy : 
```
# reseau.sebastienreycoyrehourcq.fr

upstream reseau.sebastienreycoyrehourcq.fr {
                                # Cannot connect to network of this container
                                server 127.0.0.1 down;
}
server {
        server_name reseau.sebastienreycoyrehourcq.fr;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://reseau.sebastienreycoyrehourcq.fr;
        }
}

```

Everything run well when i docker-compose up the image, but i have this error : 

monicahq_1  | Monica v2.9.0 is set up, enjoy.
monicahq_1  | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.22.0.3. Set the 'ServerName' directive globally to suppress this message

I try to understand why i had this error from nginx :

`2018/10/20 18:53:47 [error] 57#57: *81 no live upstreams while connecting to upstream, client: 90.70.26.56, server: reseau.sebastienreycoyrehourcq.fr, request: "GET / HTTP/1.1", upstream: "http://reseau.sebastienreycoyrehourcq.fr/", host: "reseau.sebastienreycoyrehourcq.fr"`

As you could see the server variable for upstream is false, it need to be : 

`172.22.0.3 up`

Any idea ?
