### ISSUE TITLE
Creating account error. Unknown column 'temperature_scale'

### ISSUE THREAD

**Issue by brusapa** [monicahq/monica#2243]
**Describe the bug**
I have deployed monica through docker-compose, when I try to sign up my first user I get this error:
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'temperature_scale' in 'field list' (SQL: insert into `users` (`account_id`, `first_name`, `last_name`, `email`, `password`, `created_at`, `locale`, `timezone`, `currency_id`, `temperature_scale`, `updated_at`) values (2, MyName, MySurname, mymail@mymailprovider.com, MyPasswordHash, 2019-01-02 08:58:31, en, America/Chicago, 2, fahrenheit, 2019-01-02 08:58:31))
```

**Docker-Compose file**
```
version: '3'
services:
  monicahq:
    image: monicahq/monicahq
    links:
      - mysql
    expose:
      - 80
    env_file: .env
    volumes:
      - /MyLocalStoragePath/monica/storage:/var/www/monica/storage
    restart: always
    labels:
      - "traefik.docker.network=proxynet"
      - "traefik.enable=true"
      - "traefik.monica.frontend.rule=Host:monica.MyDomain.com"
      - "traefik.monica.port=80"
      - "traefik.monica.protocol=http"
    networks:
      - postfixnet
      - proxynet
      - monicanet

  mysql:
    image: mysql:5.7
    container_name: monicahq-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - /MyLocalStoragePath/monica/sql:/var/lib/mysql
    restart: always
    networks:
      - monicanet

networks:
  postfixnet:
    external: true
  proxynet:
    external: true
  monicanet:
    driver: bridge
```

** .env file **
```
# Two choices: local|production. Use local if you want to install Monica as a
# development version. Use production otherwise.
APP_ENV=production

# true if you want to show debug information on errors. For production, put this
# to false.
APP_DEBUG=false

# The encryption key. This is the most important part of the application. Keep
# this secure otherwise, everyone will be able to access your application.
# Must be 32 characters long exactly.
# Use `php artisan key:generate` to generate a random key.
APP_KEY=MyKey1

# Prevent information leakage by referring to IDs with hashIds instead of
# the actual IDs used in the database.
HASH_SALT=ChangeMeBy20+KeyLength
HASH_LENGTH=18

# The URL of your application.
APP_URL=https://monica.MyDomain.com

# Database information
# To keep this information secure, we urge you to change the default password
DB_CONNECTION=mysql
DB_HOST=monicahq-mysql
DB_PORT=3306
# You can use mysql unix socket if available, it overrides DB_HOST and DB_PORT values.
#DB_UNIX_SOCKET=/var/run/mysqld/mysqld.sock
DB_ROOT_PASSWORD=MyKey2
DB_DATABASE=monica
DB_USERNAME=monica
DB_PASSWORD=MyKey3
DB_PREFIX=
DB_TEST_HOST=127.0.0.1
DB_TEST_DATABASE=monica_test
DB_TEST_USERNAME=homestead
DB_TEST_PASSWORD=MyKey4

# Use utf8mb4 database charset format to support emoji characters
# ⚠ be sure your DBMS supports utf8mb4 format
DB_USE_UTF8MB4=true

# Mail credentials used to send emails from the application.
MAIL_DRIVER=smtp
MAIL_HOST=postfix
MAIL_PORT=25
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=monicahq@MyDomain.com
MAIL_FROM_NAME="Monica HQ"
APP_EMAIL_NEW_USERS_NOTIFICATION=monicahq@MyDomain.com

# Default locale used in the application.
APP_DEFAULT_LOCALE=es

# Ability to disable signups on your instance.
# Can be true or false. Default to false.
APP_DISABLE_SIGNUP=false

# Enable user email verification.
APP_SIGNUP_DOUBLE_OPTIN=false

# Set trusted proxy IP addresses.
# To trust all proxies that connect directly to your server, use a "*".
# To trust one or more specific proxies that connect directly to your server, use a comma separated list of IP addresses.
APP_TRUSTED_PROXIES=*

# Enable automatic cloudflare trusted proxy discover
APP_TRUSTED_CLOUDFLARE=false

# Frequency of creation of new log files. Logs are written when an error occurs.
# Refer to config/logging.php for the possible values.
LOG_CHANNEL=daily

# Error tracking. Specific to hosted version on .com. You probably don't need
# those.
SENTRY_SUPPORT=false
SENTRY_LARAVEL_DSN=

# Send a daily ping to https://version.monicahq.com to check if a new version
# is available. When a new version is detected, you will have a message in the
# UI, as well as the release notes for the new changes. Can be true or false.
# Default to true.
CHECK_VERSION=true

# Change this only if you know what you are doing
CACHE_DRIVER=database
SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_DRIVER=sync

# Maximum allowed size for uploaded files, in kilobytes.
# Make sure this is an integer, without commas or spaces.
DEFAULT_MAX_UPLOAD_SIZE=10240

# Maximum allowed storage size per account, in megabytes.
# Make sure this is an integer, without commas or spaces.
DEFAULT_MAX_STORAGE_SIZE=512

# Default filesystem to store uploaded files.
# Possible values: public|s3
DEFAULT_FILESYSTEM=public

# AWS keys for S3 when using this storage method
AWS_KEY=
AWS_SECRET=
AWS_REGION=us-east-1
AWS_BUCKET=
AWS_SERVER=

# Allow Two Factor Authentication feature on your instance
MFA_ENABLED=false

# Enable CardDAV support (beta feature)
CARDDAV_ENABLED=true

# CLIENT ID and SECRET used for the official mobile application
# This is to make sure that only the mobile application that you approve can
# access the route to let your users sign in with their credentials
MOBILE_CLIENT_ID=
MOBILE_CLIENT_SECRET=

# Allow to access general statistics about your instance through a public API
# call
ALLOW_STATISTICS_THROUGH_PUBLIC_API_ACCESS=false

# Indicates that each user in the instance must comply to international policies
# like CASL or GDPR
POLICY_COMPLIANT=true

# Have access to paid features available on https://monicahq.com, for free.
# Can be true or false. Default to false.
# If set to true, that means your users will have to pay to access the paid
# features. We use Stripe to do this.
REQUIRES_SUBSCRIPTION=false

# Number of contacts allowed in the Free version if the instance requires
# a subscription
NUMBER_OF_ALLOWED_CONTACTS_FREE_ACCOUNT=10

# ONLY NECESSARY IF MONICA REQUIRES A SUBSCRIPTION TO WORK
# Leave blank unless you know what you are doing.
STRIPE_KEY=
STRIPE_SECRET=
PAID_PLAN_MONTHLY_FRIENDLY_NAME=
PAID_PLAN_MONTHLY_ID=
PAID_PLAN_MONTHLY_PRICE=
PAID_PLAN_ANNUAL_FRIENDLY_NAME=
PAID_PLAN_ANNUAL_ID=
PAID_PLAN_ANNUAL_PRICE=

# Enable geolocation services
# This is used to translate addresses to GPS coordinates.
ENABLE_GEOLOCATION=true

# API key for geolocation services
# We use LocationIQ (https://locationiq.com/) to translate addresses to
# latitude/longitude coordinates. We could use Google instead but we don't
# want to give anything to Google, ever.
# LocationIQ offers 10,000 free requests per day.
LOCATION_IQ_API_KEY=MyLocationIQApiKey

# Enable weather on contact profile page
# Weather can only be fetched if we know longitude/latitude - this is why
# you also need to activate the geolocation service above to make it work
ENABLE_WEATHER=true

# Access to weather data from darksky api
# https://darksky.net/dev/register
# Darksky provides an api with 1000 free API calls per day
# You need to enable the weather above if you provide an API key here.
 DARKSKY_API_KEY=MyDarkSkyApiKey
```

**Which version are you using:**
 - A server you maintain yourself (if so, please indicate your current version of Monica)
2.11.2

Can anyone point me out in the right direction to fix this issue?
