### ISSUE TITLE
Database not configured

### ISSUE THREAD

**Issue by JoeyKleinsorge** [monicahq/monica#2517]
**Installation on Docker failing with exception "Database [] not configured"**

Docker-compose file:
```
version: "3.2"

services:
  monicahq:
    image: monicahq/monicahq
    container_name: monica
    depends_on:
      - mysql-monica
    ports:
      - 808:80
    env_file: /volume1/docker/monica/.env
    environment:
      - PUID=1030
      - PGID=101
      - TZ="America/New_York"    
    volumes:
      - /volume1/docker/monica:/var/www/monica/storage
    restart: always

  mysql-monica:
    image: mysql:5.7
    container_name: mysql-monica
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=sekret_root_password
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - PUID=1030
      - PGID=101
      - TZ="America/New_York"      
    volumes:
      - /volume1/docker/mysql-monica:/var/lib/mysql
    restart: always

```

.env file:

```
# The URL of your application.
APP_URL=http://192.168.1.208

# Database information
# To keep this information secure, we urge you to change the default password
DB_CONNECTION=mysql-monica
DB_HOST=192.168.1.208
DB_PORT=3306
DB_DATABASE=monica
DB_USERNAME=homestead
DB_PASSWORD=secret
DB_PREFIX=
DB_TEST_HOST=127.0.0.1
DB_TEST_DATABASE=monica_test
DB_TEST_USERNAME=homestead
DB_TEST_PASSWORD=secret
```

**Screenshots**
![image](https://user-images.githubusercontent.com/30941888/54218215-84de8d80-44c3-11e9-8f8e-33719e551299.png)

**Which version are you using:**
 - Running Docker Version: 17.05.0-ce on Synology

**Additional context**
I tried using MariaDB instead but came back with the same issue. I'm not great with DBs so if anyone can help me out, I would appreciate it. Thank you. 
[laravel-2019-03-12.log](https://github.com/monicahq/monica/files/2957874/laravel-2019-03-12.log)
