### ISSUE TITLE
Where are Monica files/data stored with Docker?

### ISSUE THREAD

**Issue by al3x-huang** [monicahq/monica#3085]
I am wondering where all pictures/db files are stored. By following the instructions I would assume this would be where I specify "volumes" but the directory is empty. Here is my docker-compose.yml

version: "3.4"

```
services:
  monicahq:
    build: .
    image: monicahq/monicahq
    depends_on:
      - mysql
    ...
    volumes:
      - monica_data:/home/username/monica
    restart: always

  mysql:
    image: mysql:5.7
    ...
    volumes:
      - monica_mysql:/home/username/monica
    restart: always

volumes:
  monica_data:
    name: monica_data
  monica_mysql:
    name: monica_mysql
```

When I look in /home/username/monica I see
```
$ ls /home/username/monica/
docker-compose.yml
```

Upon further digging I ran `docker volume ls` and noticed that there were a few volumes namely

```
monica_data
monica_mysql
14023dde752...
```

monica_data and monica_mysql seem to be empty but 14023... seems to have stuff. Is this where monica files are stored?

How should I go about backing up contacts / uploaded files and pictures for Monica installed with docker?

Thanks!
