### ISSUE TITLE
Reminder emails are not being delivered (Docker, Mailgun)

### ISSUE THREAD

**Issue by cashweaver** [monicahq/monica#3127]
I have hit a wall with regard to SMTP debugging on my self-hosted instance of Monica. I'm starting this issue both to look for advice and to document my debugging process for myself and others.

## My Configuration

I am hosting the docker image of Monica (v2.15.2) on a GCP Container-Optimized instance.

```yaml
# docker-compose.yml
version: '3.7'

services:
  proxy:
    container_name: proxy
    image: jwilder/nginx-proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    networks:
      - "default"
      - "proxy-tier"
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - ./uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf:ro

  proxy-letsencrypt:
    container_name: letsencrypt
    depends_on:
      - "proxy"
    env_file: .env-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    networks:
      - "default"
      - "proxy-tier"
    restart: unless-stopped
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  monicahq:
    build: .
    depends_on: 
      - mysql
    env_file: .env-monicahq
    image: monicahq/monicahq
    networks: 
      - "default" 
      - "proxy-tier"
    ports: 
      - 3000:80
    restart: always
    volumes: 
      - monica_data:/var/www/monica/storage

  mysql:
    env_file: .env-mysql
    image: mysql:5.7
    restart: always
    volumes: 
      - monica_mysql:/var/lib/mysql

volumes:
  certs:
  html:
  monica_data: 
    name: monica_data
  monica_mysql: 
    name: monica_mysql
  vhost.d:

networks:
  proxy-tier:
```

```txt
# .env-monicahq
# Mail credentials used to send emails from the application.
MAIL_DRIVER=mailgun
MAIL_HOST=smtp.mailgun.com
MAIL_PORT=587
MAIL_USERNAME=postmaster@<mailgun domain>
MAIL_PASSWORD=<password>
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=monica@<mailgun domain>
MAIL_FROM_NAME="Monica"

MAILGUN_DOMAIN=<mailgun domain>
MAILGUN_SECRET=<mailgun secret>
```

## Reproduction steps

- `docker-compose up`, then `docker exec -i $(docker-compose ps -q monicahq) php artisan send:reminders`
- The "Time of the day reminders should be sent" configured per #1020 to be the current hour (eg: the field is set to 08:00 AM when it is 08:24 AM)
- The reminder is set to be sent on the current day
