### ISSUE TITLE
[Docker] apache image doesn't work

### ISSUE THREAD

**Issue by nemoload** [monicahq/monica#3358]
This is my `docker-compose.yml`:
```yml
version: "3.7"
services:
  app:
    image: monicahq/monicahq
    ports:
      - 8080:80
    env_file: .env
    volumes:
      - /tmp/monica:/var/www/monica/storage
    restart: always
    networks: 
      - monica-mysql
networks:
  monica-mysql:
    external: true
    name: mysql-network
```
When I run it and try to open it from the browser it gives me this error: `The stream or file "/var/www/monica/storage/logs/laravel-2019-12-25.log" could not be opened: failed to open stream: Permission denied`
