### ISSUE TITLE
Relative URLs redirection doesn't work when using a proxy

### ISSUE THREAD

**Issue by nemoload** [monicahq/monica#3361]
I have monica running in a **docker container with apache** and I use another **nginx** instance to act as a **proxy** to the container, it serves monica from `http://localhost/monica` where the docker container is running on `http://localhost:8030/`. I ave also set `APP_URL=http://localhost/monica`

The problem is that every relative url redirection from `window.location` returns Error 404 as `window.location` doesn't respect the html base location previously set through `APP_URL` environment variable.

My suggestion: change every `window.location = '/realtive_url'` to something like `window.location = document.querySelector('base').href + 'relative_url'`

My NGINX configuration
```nginx
        location ~/monica(.*)$ {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Host $host;
            proxy_pass http://127.0.0.1:8030$1;
            proxy_redirect ~http://localhost/(.*) /monica/$1;
            sub_filter "http://localhost/" "http://localhost/monica/";
            sub_filter_once off;
        }
```
My docker-compose configuration:
```yml
version: "3.7"
services:
  app:
    image: monicahq/monicahq
    ports:
      - 8030:80
    env_file: 
      - .env
    volumes:
      - /var/www/monica/storage:/var/www/monica/storage
    restart: always
    networks: 
      - monica-mysql
networks:
  monica-mysql:
    external: true
    name: mysql-network

```
