### ISSUE TITLE
Unable to run app using docker compose locally

### ISSUE THREAD

**Issue by cabello** [monicahq/monica#3363]
**Describe the bug**

I tried following the [documentation to setup an instance locally using Docker](https://github.com/monicahq/monica/blob/632c0c3c3b5fb4c2e6dad1b4f64a32d7d3392583/docs/installation/docker.md).

I chose the FPM version and once the containers were up I tried loading the application and got "Whoops! Something went wrong" page, after some research I tried a few different things, this is how my `docker-compose.yml` looks like, note that I added a few comments on relevant lines:

```yml
version: "3.4"

services:
  app:
    image: monicahq/monicahq:fpm
    depends_on:
      - mysql
    environment:
      - APP_KEY=5KilLarCr4BDHJxARrwgz0xIcM1NM75s
      - APP_DEBUG=1 # display useful error messages
      - APP_EMAIL_NEW_USERS_NOTIFICATION=noreply@localhost.com # from https://github.com/monicahq/monica/issues/2175
      - DB_DATABASE=monica # seem required from config/database.php
      - DB_HOST=mysql
      - DB_PASSWORD=secret # seem required from config/database.php
      - DB_USER=homestead # seem required from config/database.php
    volumes:
      - html:/var/www/monica
      - data:/var/www/monica/storage
    links:
      - mysql # allow containers to talk to each other
    restart: always
  
  web:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - html:/var/www/monica:ro
      - data:/var/www/monica/storage:ro
    restart: always

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=9xmkYcstMCU2tT3Tgq3bTUDUYQK4fYsP
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql
    restart: always

volumes:
  data:
    name: monica_data
  html:
    name: monica_html
  mysql:
    name: monica_mysql
```

After turning debugging on, this is the error I've got: `SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `cache` where `key` = laravel_cachecloudflare.proxies limit 1)`.

I suspect my setup is not allowing the app to communicate with the mysql container. I tried `links`, I also tried setting `DB_` env variables from looking at the source.

Any pointers or things I should try? 

Thank you for making this project open source, I appreciate it.
