### ISSUE TITLE
Cannot get monica set up with Docker (Access denied for user)

### ISSUE THREAD

**Issue by fosspill** [monicahq/monica#3702]
**Describe the bug**
Using docker-compose to set up, as described by the documentaiton, results in the error "Access denied for user" in console and the stup fails.

I'm sure I did something stupid, but I cannot figure it out.


**Additional context**
```
# docker-compose exec app php artisan migrate         

In Connection.php line 669:
                                                                                                                                                                                                                                     
  SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'172.18.0.3' (using password: YES) (SQL: select * from information_schema.tables where table_schema = monica and table_name = migrations and table_type = 'BASE TABLE')  
                                                                                                                                                                                                                                     

In PDOConnection.php line 31:
                                                                                                
  SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'172.18.0.3' (using password: YES)  
                                                                                                

In PDOConnection.php line 27:
                                                                                                
  SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'172.18.0.3' (using password: YES) 
```

**docker-composer.yml**:
```
version: "3.4"

services:
  app:
    image: monicahq/monicahq
    depends_on:
      - mysql
    ports:
      - 9000:80
    environment:
      - APP_KEY=49fVmorL8u4rIRHCyxbkParpVoptfoQw
      - DB_HOST=mysql
    volumes:
      - data:/opt/monicahq
    restart: always

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=OQe1Zw9EVc8OjfAUjFXCBhi1eb3GAxI4
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql
    restart: always

volumes:
  data:
    name: data
  mysql:
    name: mysql
```
