### ISSUE TITLE
Cannot get email to work (docker)

### ISSUE THREAD

**Issue by fosspill** [monicahq/monica#3844]
Hi!

I have a docker running postfix for me and it works fine with all other services (amongst others watchtower).

However, when I configure Monica the exact same way I keep getting this errer:
`Connection could not be established with host 172.27.0.2 :stream_socket_client(): unable to connect to 172.27.0.2:9587 (Connection refused)`

The Monica docker is connected to the same docker network as both watchtower and postfix.

Am I missing something obvious?

Monica docker-compose:
```
version: "3.4"

services:
  app:
    image: monicahq/monicahq
    depends_on:
      - mysql
    ports:
      - 9000:80
    environment:
      - APP_KEY=******
      - DB_HOST=mysql
      - MAIL_DRIVER=smtp
      - MAIL_HOST=172.27.0.2 
      - MAIL_PORT=9587
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - MAIL_ENCRYPTION=
      - MAIL_FROM_ADDRESS=web@*****
      - MAIL_FROM_NAME=Monica CRM
    volumes:
      - data:/opt/monicahq/data
    restart: always

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=**************
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    volumes:
      - mysql:/opt/monicahq/mysql
    restart: always

volumes:
  data:
    name: data
  mysql:
    name: mysql

networks:
  default:
    external:
      name: postfixNetwork
```

Watchtower docker-compose, which works fine:
```
version: '3'
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=web@******
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=******
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=172.27.0.2
      - WATCHTOWER_NOTIFICATION_EMAIL_PORT=9587
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
networks:
  default:
    external:
      name: postfixNetwork
```
Network inspect
```
        "Containers": {
            "341d3d716ad5afae76d045d1aabfd74a5f581729468de9df662bf816b3fb6027": {
                "Name": "watchtower",
                "EndpointID": "bed5e35800cb8d4a7282adc4ddbb4939ff34bf19d967353065a9af2aa7e6303b",
                "MacAddress": "02:42:ac:1b:00:03",
                "IPv4Address": "172.27.0.3/16",
                "IPv6Address": ""
            },
            "4243446e8f57cfaaedf696e7793d9b1b17618ad3f1212415cc15d7117e1f9601": {
                "Name": "monica-docker_mysql_1",
                "EndpointID": "1723de5f8a89a550424850b247cb28e4fe8ae3ef1c453d92084159883064b7fb",
                "MacAddress": "02:42:ac:1b:00:04",
                "IPv4Address": "172.27.0.4/16",
                "IPv6Address": ""
            },
            "99c5c2780f019fa59cdc725107d0eaec7aad03b651b5a696cf755ae1fac6632e": {
                "Name": "postfix",
                "EndpointID": "c125ff97a154c61dca9bf663e3efcda98d467a8e13af5fb80acaa5220c6b88f4",
                "MacAddress": "02:42:ac:1b:00:02",
                "IPv4Address": "172.27.0.2/16",
                "IPv6Address": ""
            },
            "af6b4b00af521c25cc6460e5eb6cff3d26d3e268dce5048c59f79b983cfca7fa": {
                "Name": "monica-docker_app_1",
                "EndpointID": "3070af73987a3fa81e90afee0669ecedf9e47034c32500f6620b0eb5fbaa6da3",
                "MacAddress": "02:42:ac:1b:00:05",
                "IPv4Address": "172.27.0.5/16",
                "IPv6Address": ""
            }
        },

```
