### ISSUE TITLE
Action Facade\Ignition\Http\Controllers\ExecuteSolutionController not defined

### ISSUE THREAD

**Issue by cashweaver** [monicahq/monica#3860]
**Describe the bug**
I see a "Action Facade\Ignition\Http\Controllers\ExecuteSolutionController not defined" error when attempting to save a change to the "Time of the day reminders should be sent" in /settings.

**Screenshots**
![1587237501_1218_18042020_1073x1433](https://user-images.githubusercontent.com/56796112/79669835-67bec880-8173-11ea-9356-724ab11d804b.png)

**Which version are you using:**
Docker, monica/monica:fpm, Version: 2.17.0.

**Additional context**
This error occurs with a fresh container. The steps taken before attempting to save the time are:

1. Stop all monica docker containers (`docker-compose down`)
1. Destroy all monica docker containers (`docker system prune --volumes`)
1. Start the database container, let it complete it's set up, then stop it (`docker-compose up db`)
1. Start the Monica, database, and web containers as detached (`docker-compose up -d monica web db`)
1. Create first user account (/register)
1. Run setup:production (`docker-compose exec -T monica php artisan setup:production --force`)
1. Remove log file with inappropriate file permissions, see #575 (`docker-compose exec -T monica rm /var/www/monica/storage/logs/laravel-2020-04-18.log`)
1. Visit the settings page (/settings) and attempt to update the "Time of the day reminders should be sent".

**Comment by cashweaver** [comment]
docker-compose.yaml:
```yaml
version: '3.7'

services:
  monica:
    depends_on:
      - db
    env_file: 
      - ./monica/.env 
      - ./monica/.env-secrets
    image: monicahq/monicahq:fpm
    restart: always
    volumes: 
      - vol-data:/var/www/monica/storage 
      - vol-www:/var/www/monica

  cron:
    command: cron.sh
    depends_on: 
      - db
    env_file: 
      - ./monica/.env
      - ./monica/.env-secrets
    image: monicahq/monicahq:fpm
    restart: always
    volumes: 
      - vol-data:/var/www/monica/storage
      - vol-www:/var/www/monica:ro

  queue:
    command: queue.sh
    depends_on: 
      - db
    env_file: 
      - ./monica/.env
      - ./monica/.env-secrets
    image: monicahq/monicahq:fpm
    restart: always
    volumes: 
      - vol-data:/var/www/monica/storage
      - vol-www:/var/www/monica:ro

  db:
    env_file:
      - ./db/.env
      - ./db/.env-secrets
    image: mysql:5.7
    restart: always
    volumes: 
      - vol-mysql:/var/lib/mysql

  web:
    build: ./web
    depends_on:
      - monica
    env_file:
      - ./web/.env
    restart: always
    volumes:
      - vol-data:/var/www/monica/storage:ro
      - vol-www:/var/www/monica:ro

volumes:
  vol-data: 
    name: vol-data
  vol-www: 
    name: vol-www
  vol-mysql:
    name: vol-mysql

networks:
  default:
    external:
      name: nginx-proxy
```

Other files can be seen in my [self-hosted repo](https://github.com/cashweaver/self-hosted/tree/7c8ec8824f283f20e4807b8c82862f2c06c56019/monica).
