### ISSUE TITLE
Not working behind proxy with HSTS policy

### ISSUE THREAD

**Issue by OnlyFreeUsername** [monicahq/monica#4935]
**Describe the bug**
I'm currently trying to serve monica (docker image) behind an nginx reverse proxy. To prevent every possible leaks I activated the HTTP Strict Transport Security policy on my proxy. After I setup the proxy_set_header monica now correctly used my proxy forwarded host as the resource location. Monica seems to completely ignore the APP_URL that i set as https://monica.mydomain.com

**Screenshots**
![image](https://user-images.githubusercontent.com/18463421/110089320-428c7600-7d96-11eb-9f12-78cd90cc052c.png)

**Which version are you using:**
I'm using the latest version. Here is my current composition:
```
version: "3.4"

services:
  app:
    image: monica
    depends_on:
      - db
    ports:
      - 127.0.0.1:9020:80
    environment:
      - APP_URL=https://monica.mydomain.com
      - APP_KEY=myappkey
      - DB_HOST=db
      - MAIL_MAILER=smtp
      - MAIL_HOST=mail.mydomain.com
      - MAIL_PORT=587
      - MAIL_USERNAME=monica@mydomain.com
      - MAIL_PASSWORD=passwd
      - MAIL_ENCRYPTION=TLS
      - MAIL_FROM_ADDRESS=monica@mydomain.com
      - MAIL_FROM_NAME=Monica
      - ENABLE_GEOLOCATION=true
      - LOCATION_IQ_API_KEY=pk.myapikey
    volumes:
      - ${DATA_DIR}/storage:/var/www/html/storage
    restart: always

  db:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    volumes:
      - ${DATA_DIR}/db:/var/lib/mysql
    restart: always
```

**Additional context**
Monica listens to port 9020 and is behind a reverse proxy providing ssl. I configured nginx like this:
```
        # Monica
        server {
                listen  443 ssl http2;
                server_name     monica.mydomain.com;
                add_header      Strict-Transport-Security max-age=31536000;

                location / {
                        proxy_set_header        Host $http_host;
                        proxy_set_header        X-Real-IP $remote_addr;
                        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_set_header        X-Forwarded-Proto $scheme;
                        proxy_pass      http://127.0.0.1:9020/;
                }
        }
```

Notice that in the screenshot the file "/img/monica.svg" was served correctly via https while the favicon and the "/css/app-ltr.css?id=3656924c5fce352ba736" files were requested via http and thus blocked by the HSTS policy.
