### ISSUE TITLE
Periodically unable to connect to db

### ISSUE THREAD

**Issue by davidmritter** [monicahq/monica#5024]
**Describe the bug**
Fairly often I get the message `SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'172.18.0.2' (using password: YES) (SQL: select * from `cache` where `key` = laravel_cachecloudflare.proxies limit 1)`

Sometimes instead of the message, content is missing, for example instead of:
![Expected](https://user-images.githubusercontent.com/30492270/113421425-5375da80-9388-11eb-8117-47e6181dea76.png)
I get this:
![missing_calls](https://user-images.githubusercontent.com/30492270/113421426-540e7100-9388-11eb-9644-3bfb9996742b.png)

This is not the only page or information, it can be contact missing tags or call log details.

**Version**
 - Self hosted version: 2.20.0

**Additional context**
Using docker compose, config file include(passwords changed)
```yaml
version: '3'

services:
  app:
    image: monica
    hostname: monica
    domainname: davidritter.ca
    depends_on:
      - db
    environment:
      - APP_KEY=some-key-value
      - DB_HOST=db
      - APP_URL=http://monica.davidritter.ca
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.ionos.com
      - MAIL_PORT=587
      - MAIL_USERNAME=monica@davidritter.ca
      - MAIL_PASSWORD=some-email-password
      - MAIL_ENCRYPTION=STARTTLS
      - MAIL_FROM_NAME="Monica"
      - DB_USERNAME=homestead
      - DB_PASSWORD=some-db-passowrd
    ports:
      - 8080:80
    volumes:
      - /docker/monica-main:/var/www/html/storage
    restart: always
    
  db:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=some-db-passowrd
    volumes:
      - /docker/monica-db:/var/lib/mysql
    restart: always


networks:
  default:
    external:
      name: main

```
