### ISSUE TITLE
Scheduled emails not working on self-install of Monica (no cron in container)

### ISSUE THREAD

**Issue by cstrat** [monicahq/monica#5084]
I've installed Monica via `docker-compose`.
Largely following the guide on docker-hub for the Apache version: https://hub.docker.com/_/monica
Things that appeared to be missing from that guide are the fact email config needs to be included in the app environment block in docker-compose. I did read the linked section on docker-compose, but I was't sure how downloading the example `.env` file would integrate with the docker setup. (https://github.com/monicahq/docker/tree/master/.examples)

Now my issue with scheduled emails not working is because cron is missing from the container.
The docker-compose example doesn't include any information on this.
It looks like `crontab` itself is setup correctly - just cron is not installed.

![image](https://user-images.githubusercontent.com/4209076/115640326-07500180-a35a-11eb-9848-52ee5fc0f223.png)

So I've manually installed cron inside the container (and had to manually start the service), but that manual step will need to be done each time I rebuild the container.

What is best practice here?

This is probably a very easy thing to do if I had a better understanding on how docker is supposed to be setup.
I'd be happy to help contribute to update the guide - but I don't know the most correct answer myself.

**Comment by cstrat** [comment]
Ok strange but installing and running cron did not solve the issue. Still didn't receive a test email for a reminder.
I even tried to do the supervisord thing, but couldn't get that working using the `build` bit in the docker-compose file.

Guess I will be without notifications until I learn more about how this is plumbed together.

**Comment by zeezhao** [comment]
Hi. Also have a look at some of the comments in https://github.com/monicahq/monica/issues/4178, to see if related...

**Comment by peetersdaan** [comment]
Hey @cstrat and @zeezhao, today I reinstalled Monica with Supervisor in a new container but I'm also still running into this issue (see for more information https://github.com/monicahq/docker/issues/48) 
![Screenshot 2021-04-23 at 19 27 19](https://user-images.githubusercontent.com/53089641/115909043-3c984480-a46b-11eb-915d-34ebecfda140.jpg)

**Comment by cstrat** [comment]
Ok now that `supervisord` is installed it is all working with scheduled alerts working!
I'll close this issue and leave my setup information for anyone facing the same issue...

My issue can be summarised as me not understanding what docker was doing.
I did not understand what the `build` step was doing.
I hadn't download the build (app) directory for my `docker-compose`, so I wasn't running that step and I thought manual intervention was required.

FYI this is my `docker-compose.yml` file which works perfectly for me now.

````
version: "3.4"

services:
  app:
    build: ./setup
    image: monica-app
    depends_on:
      - db
    ports:
      - 8555:80
    environment:
      - APP_KEY=xxxx
      - DB_HOST=db
      - APP_ENV=production
      - APP_URL=xxxx
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.mailgun.org
      - MAIL_PORT=587
      - MAIL_USERNAME=xxxx
      - MAIL_PASSWORD=xxxx
      - MAIL_ENCRYPTION=tls
      - MAIL_FROM_ADDRESS=xxxx
      - MAIL_FROM_NAME=Monica

    volumes:
      - ./app:/var/www/html/storage
    restart: always

  db:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=xxxx
      - MYSQL_PASSWORD=xxxx
    volumes:
      - ./db:/var/lib/mysql
    restart: always
````

In the directory `./setup` I have the two files, `Dockerfile` and `supervisord.conf` copied form [here](https://github.com/monicahq/docker/tree/master/.examples/supervisor/apache/app).

You will notice I am not using the `.env` file, mainly because I got it working prior to realising that was an option - and I don't want to mess with it. Plus I think I've addressed the main env variables in the `docker-compose.yml` file.

In my setup, I now have a directory with my docker-compose file, the setup dir and my mounted volumes. So backing this up is quite simple, I just rsync the whole dir and I should be able to restore by just copying the whole folder.
