### ISSUE TITLE
"Events in the next 3 months" is empty despite having contacts populated with valid reminders & events

### ISSUE THREAD

**Issue by dchakro** [monicahq/monica#5477]
Since the month of June I have not been getting any reminders and neither do they display in the "Events in the next 3 months" on the dashboard. It just shows "No reminders for this month". Oddly enough there is this one event I noticed being displayed today after a long period with "No reminders".
<img width="530" alt="Events in the next 3 months" src="https://user-images.githubusercontent.com/35454738/132076378-5cde1333-fe86-4b82-bcc6-80940a5afd91.png">

I thought it could be a bug in a minor version and will get sorted out and updated monica today to 3.2.0 but the problem still exists. Although my dashboard looks like the screenshot above, I know for a fact there are several of my contacts with birthdays and events in the next few months. In the example contacts below, I can see the reminders being listed when I search & open the individual contacts.

![Contacts with events in next few months](https://user-images.githubusercontent.com/35454738/132076192-e214a3fb-d700-4852-b942-3b8cff8c57fe.jpg)

**Troubleshooting:**
running `php artisan monica:test-email` works. I have the reminders configured via `supervisord` and they used to work fine before the end of June.

What can I do to investigate what went wrong with my database / monica instance. It has been frustrating missing important dates.

Information:
Running Monica v 3.2.0 with this docker-compose and Dockerfile.

```yaml
version: "3.4"

services:
  app:
    build: ./app
    image: monica-app
    depends_on:
      - mysql
    env_file: .env
    ports:
      - 82:80
    volumes:
      - /srv/monicahq/monica:/var/www/html/storage
    restart: always

  mysql:
    image: mysql:5.7
    container_name: monicahq-mysql
    ports:
        - 3306:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=SuperSecretPassword
    volumes:
      - /srv/monicahq/mysql:/var/lib/mysql
    restart: always% 
```

```properties
# contents of DOCKERFILE
FROM monica:apache

# Use the default production configuration
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

# supervisord dependencies
RUN set -ex; \
    \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        supervisor \
    ; \
    rm -rf /var/lib/apt/lists/*

COPY supervisord.conf /etc/supervisord.conf

CMD ["supervisord", "-c", "/etc/supervisord.conf"]
```
