### ISSUE TITLE
"The vcard failed to upload." error while importing contacts

### ISSUE THREAD

**Issue by carsondarling** [monicahq/monica#5659]
**Describe the bug**
When importing a `.vcf` file exported from MacOS Contacts, Monica responds with "The vcard failed to upload." The file is 3.6MB. If I upload a single contact at a time, everything works fine.

I'm hosted using the supervisor docker-compose example, with my docker-compose.yml file shown below. I'm running a separate Nginx reverse proxy (not shown below) to handle HTTPS termination.

This appears to be another instance of #2354.

**Which version are you using:**
 - Version 3.3.1 from `monica:fpm-alpine`

**Additional context**

```yml
# docker-compose.yml
version: "3.4"

services:
  app:
    build: ./app
    depends_on:
      - db
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_USERNAME=<redacted>
      - DB_PASSWORD=<redacted>
    volumes:
      - data:/var/www/html/storage
    restart: always
  networks:
      - proxy_default

  web:
    build: ./web
    restart: always
    expose:
      - "80"
    volumes:
      - data:/var/www/html/storage:ro
    depends_on:
      - app
    environment:
      VIRTUAL_HOST: <redacted>
      LETSENCRYPT_HOST: <redacted>
      LETSENCRYPT_EMAIL: <redacted>
    networks:
      - proxy_default

  db:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=<redacted>
      - MYSQL_USER=<redacted>
      - MYSQL_PASSWORD=<redacted>
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    networks:
      - proxy_default

volumes:
  data:
  mysql:

networks:
  proxy_default:
    external: true
```
