### ISSUE TITLE
Not receiving reminders

### ISSUE THREAD

**Issue by adamleerosenfeld** [monicahq/monica#5681]
Hi, I set reminders to keep in touch with my contacts.

I rely on them.

But I'm not getting any of the reminders.

Any idea why that is?

Thanks, 

Adam

**Comment by JonTheNiceGuy** [comment]
This is because you need to have some process that sends the reminders. If you're using the docker-compose file, add a stanza similar to the one below, but with your details in, to add a Cron container:

```
cron:
    image: monica:fpm
    restart: always
    command: cron.sh
    depends_on:
      - db
    environment: <as per main app container>
    volumes: <as per main app container>
```

**Comment by adamleerosenfeld** [comment]
Thanks for the reply!

I'm just a user, not a programmer.

The fix you suggested is lost on me :-(

Any other way to get this fixed?

I run Monica in my browser.

Thanks,

Adam

**Comment by JonTheNiceGuy** [comment]
Hi @adamleerosenfeld are you running the Monica server yourself, is a friend or similar running it for you, are you using the paid service from monicahq.com (or similar), or are you doing something different?

Essentially, if you're hosting it yourself, you'd need to let me know how you set it up. If someone else is hosting it for you, then they need to look at the notes I put above. If it's a paid service, then you'll need to contact their support team. Something else? Um, drop a note in to give me more details :)

**Comment by adamleerosenfeld** [comment]
Thanks, I'm using the service from monicahq.com. I reached out on github
because I got no reply from Monica support :-(

**Comment by b3nd1k** [comment]
You're not alone, I'm not receiving any email notifications on my self hosted instance either. I have tested `email using: php artisan monica:test-email` and that works, but besides that I get no emails. 

I've tried adding `CRON_LEGACY=true` as a docker variable, as I've seen someone else have had luck with it , but it did not resolve my issue.

**Comment by Tabularasah** [comment]
Notifications also not working here on a self-hosted instance. Email is working but Monica is not sending out reminders or notifications for keeping in contact.

**Comment by sasimpson** [comment]
I am having a similar issue with reminders.  The dashboard will not update unless i go into a contact and save the contact again.  Once i do that, they show up in the dashboard.  Self hosted, docker-compose

**Comment by hwrdtm** [comment]
+1 having issues too

**Comment by luca-sambuca** [comment]
+1 same here...

**Comment by starlord998** [comment]
Has anyone found a solution to receiving email reminders? I am running Monica in a docker container?

**Comment by JonTheNiceGuy** [comment]
@starlord998 If you're using Docker Compose to start your container, then I've got a stanza (from up [there](https://github.com/monicahq/monica/issues/5681#issuecomment-980795951)) you can add which will solve it.

```
cron:
    image: monica:fpm
    restart: always
    command: cron.sh
    depends_on:
      - db
    environment: <as per main app container>
    volumes: <as per main app container>
```

If you're just running docker commands on your CLI, then you'll need to run something like:

```
docker run --restart=always monica:fpm cron.sh
```

I've not included any `--env`/`-e` or `--volume`/`-v` switches, because that will depend on what you've already got configured. I also can't see how to have a "depends on" statement in the docker run cli switches.
