### ISSUE TITLE
Support Docker secrets

### ISSUE THREAD

**Issue by DennisGaida** [monicahq/monica#5809]
**Is your feature request related to a problem? Please describe.**
* Currently the documentation states to use .env files / environment variables to pass secrets to run MonicaHQ with docker compose / docker. I would love to make use of **docker secrets**: https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets instead of having secret things in my .env file.

**Describe the solution you'd like**
Support docker secrets. Either by adding new environment variables such as `DB_PASS_FILE` which actually does a `cat /run/secrets/DB_PASS_FILE` inside the container - or we could have some logic that checks whether `/run/secrets/DB_PASS` exists and overwrites whatever is in environment variable `DB_PASS`.

**Describe alternatives you've considered (optional)**
Have my secrets in the .env file

**Comment by asbiin** [comment]
Hi. Is the change needed only on the documentation part?

**Comment by DennisGaida** [comment]
Documentation is secondary, but important - Monica HQ does not implement docker secrets AFAIK.

I would love my docker-compose to look like this:
```
version: "3.7"

secrets:
  monicahq_db_password:
    file: $SECRETSDIR/monicahq_db_password

services:
  monicahq:
    image: monicahq/monicahq:latest
    container_name: monica
    environment:
      - DB_PASSWORD_FILE=/run/secrets/monicahq_db_pasword
    secrets:
      - monicahq_db_password
```
But I currently have to use hardcoded passwords or the `.env` file like so (which isn't best practice anymore for secrets):
```
services:
  monicahq:
    image: monicahq/monicahq:latest
    container_name: monica
    environment:
      - DB_PASSWORD=${MONICAHQ_DB_PASS}
```
