### ISSUE TITLE
 settings.export_status_failed When trying to export SQL & Json backups

### ISSUE THREAD

**Issue by tladder** [monicahq/monica#5937]
**Describe the bug**
I've recently imported a database from a v3.5.0 docker instance into a fresh 3.6.1 docker setup. After looking to make an export of the 3.6.1 database for backup purposes, I receive the following error:  settings.export_status_failed (Also seen in the screenshot)

**Screenshots**
![Capture2](https://user-images.githubusercontent.com/97402330/151683349-429a3e9a-330e-4f8f-a0be-8526043fdf5b.PNG)

**Which version are you using:**
A self-hosted Ubuntu 20.04 full VM running the latest docker and docker-compose. I've used phpmyadmin to import the 3.5 database into the 3.6.1 database.

My docker-compose file:

```
version: "3.4"

services:
  app:
    image: monica
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - APP_KEY=REDACTED
      - DB_HOST=db
      - DB_USERNAME=usermonica
      - DB_PASSWORD=secret
      - DEFAULT_MAX_UPLOAD_SIZE=500000
    volumes:
      - data:/var/www/html/storage
    restart: always

  db:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=usermonica
      - MYSQL_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql
    restart: always

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: pma
      links:
        - db
      environment:
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
      restart: always
      ports:
        - 8081:80
   
volumes:
  data:
    name: data
  mysql:
    name: mysql
  dbdata:
```
