### ISSUE TITLE
Apache 408 Error: Server timeout waiting for the HTTP request from the client. 

### ISSUE THREAD

**Issue by fpichl** [monicahq/monica#6081]
Hi y'all,

I set up monica via docker-compose and started the containers. I could connect via my browser and saw the register page, but after reloading or clicking any links, I always get this:

```
Request Timeout
Server timeout waiting for the HTTP request from the client.

Apache/2.4.53 (Debian) Server at 172.19.0.3 Port 80
```
monica runs on my raspberry pi (armv7l, Raspbian GNU/Linux 10 buster) and I tried connecting via ssh port forwarding, and by using lynx locally. Both show this error.

I don't really know how to tackle the problem from here on out. Any help or pointer in the right direction is greatly appreciated!

my docker-compose file:
```
version: "3.4"

services:
  app:
    image: monica
    env_file: .env
    depends_on:
      - db
    ports:
      - 8182:80
    volumes:
      - /home/pi/monicahq/storage:/var/www/html/storage
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  cron:
    image: monica
    env_file: .env
    restart: always
    volumes:
      - /home/pi/monicahq/storage:/var/www/html/storage
    command: cron.sh
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  db:
    image: jsurf/rpi-mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: <password>
      MYSQL_DATABASE: <username>
      MYSQL_USER: homestead
      MYSQL_PASSWORD: <password>
    volumes:
      - /home/pi/monicahq/mysql:/var/lib/mysql
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

volumes:
  data:
    name: data
  mysql:
    name: mysql
```

my .env file:

```
APP_KEY=<app-key>
APP_URL="raspberrypi.local:8080"

APP_ENV=local

DB_HOST=monicahq_db_1

DB_USERNAME=homestead
DB_PASSWORD=<password>

MAIL_MAILER=smtp
MAIL_HOST=<host>
MAIL_PORT=<port>
MAIL_USERNAME=<username>
MAIL_PASSWORD=<password>
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=<adress>
MAIL_FROM_NAME=Monica
```
