### ISSUE TITLE
Trouble installing monica on Synology Docker

### ISSUE THREAD

**Issue by sysgc** [monicahq/monica#6097]
Hi, 

DSM 7.0

I have tried installing monica on synology NAS using docker using docker-compose, portainer, the inbuilt UI and yet i cant seem to get the installation successful. I have basic issues with permissions or the app connecting to DB. i have tried mysql and mariadb but cant seem to get either. the attempt below is mariadb - 

  [Illuminate\Database\QueryException (HY000)]
  SQLSTATE[HY000]: General error: 1005 Can't create table `monica`.`migration
  s` (errno: 13 "Permission denied") (SQL: create table `migrations` (`id` in
  t unsigned not null auto_increment primary key, `migration` varchar(191) no
  t null, `batch` int not null) default character set utf8mb4 collate 'utf8mb
  4_unicode_ci')

Everything is pretty much default, expect the exposed DB port. i changed it to a custom port as i have other apps using mariadb (i have a separate db install for each app that requires it) i have followed steps from various websites, but just cant seem to get it installed. i have been able to get other lavarel apps (firefly for one) to work successfully. 

Any help is appreciated. Thanks.

**Comment by Eamourinho** [comment]
I managed to get it working using a Portainer stack, created a monica folder in my docker mount and used this compose. Make sure you change the mysqlpass and update the volume paths to reflect your env:
```
version: "3.4"

services:
  app:
    image: monica
    depends_on:
      - db
    ports:
      - 4166:80
    environment:
      - DB_HOST=db
      - DB_USERNAME=monica
      - DB_PASSWORD=<mysqlpass>
    volumes:
      - /volume2/docker/monica/storage:/var/www/html/storage
    restart: always

  db:
    image: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=<mysqlpass>
    volumes:
      - /volume2/docker/monica/mysql:/var/lib/mysql
    restart: always
```
