### ISSUE TITLE
Fatal error: Uncaught Error: Class "mysqli" not found in Standard input code:34

### ISSUE THREAD

**Issue by purashy** [monicahq/monica#6199]
Hello Guys,

Fresh install of MonicaHQ (changing nothing besides volumes and DB password) shows the following error:

``` 
 APP_KEY already set
 Fatal error: Uncaught Error: Class "mysqli" not found in Standard input code:34
 
 Stack trace:
 
 }
   thrown in Standard input code on line 34
```

My docker-compose.yml below:

```
version: "3.4"

services:
  app:
    image: monica
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - APP_KEY=base64:xxxxx
      - DB_HOST=db
      - DB_USERNAME=monica
      - DB_PASSWORD=xxxxxx
    volumes:
      - /monica/php:/usr/local/etc/php
      - /monica/data:/var/www/html/storage
    restart: always

  db:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=xxxx
    volumes:
      - /monica/mysql:/var/lib/mysql
    restart: always
```
