### ISSUE TITLE
Journal Import

### ISSUE THREAD

**Issue by AdamGaffney96** [monicahq/monica#6550]
This is kind of a feature request and kind of a question. I have been keeping a local journal on a mobile app for about 3 years and want to move this into Monica. Understandably I don't want to type in every single entry so I was hoping to just import my exported CSV into the table. I'm familiar with SQL so was going to import this myself by connecting to the database but I keep getting "connect ECONNREFUSED <server-ip>:3306" whenever trying to connect to the database. So I suppose I have multiple questions.

1. Is this a feature already in that I haven't found yet, and if not is it planned for?
2. Are there any ideas as to why my connection may not be working? I'm using the correct database credentials I being so confused as to why I'm getting the error. My docker-compose for the DB is below.
```
db:
    image: mysql
    container_name: Monica-DB
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=secret
    volumes:
      - /volume1/docker/monicadb:/var/lib/mysql
    restart: always
```
The details I'm using to try connect are below
```
Server Address: 192.168.0.xxx where this is the local IP for my Synology NAS server that's hosting it (also note monica and monicadb are in docker, not sure if relevant).
Port: 3306
Database: monica
Username: monica
Password: (I have tried both "secret" and the generated root password, both gave the ECONNREFUSED error)
```
Hope someone has some advice, thanks!
