### ISSUE TITLE
 Cannot persist database with Chandler on Docker

### ISSUE THREAD

**Issue by cellulosa** [monicahq/monica#6929]
## Bug description

Hi there, I just got up and running the latest version of Monica (Chandler) on Docker following [this](https://docs.monicahq.com/developers/docker) and looking at the [examples](https://github.com/monicahq/docker/tree/main/.examples) and the [example configuration file](https://raw.githubusercontent.com/monicahq/monica/main/.env.example).

I noticed the image only runs if the database in *not* declared so as to persist it.
That means, as soon as I add a volume (`~/monica/database.sqlite:/database/database.sqlite`) and/or set `DB_DATABASE=/database/database.sqlite`, Monica is unable to read/write and therefore it all goes bananas.
I tried to play with user permissions and even chowing 777 my local folder but nothing. Best case I can see the file is being written on startup (because it goes from 0 to 569 KB, but I am unable to create a new user).

## How to reproduce

Add the following on `docker-compose.yml` and start with `docker-compose up`.

This works:

```
monica:
  container_name: monica
  image: ghcr.io/monicahq/monica-next:main
  ports:
    - 8080:80
  environment:
    - MAIL_MAILER=log
  restart: unless-stopped
```

This *doesn't*:

```
monica:
  container_name: monica
  image: ghcr.io/monicahq/monica-next:main
  ports:
    - 8080:80
  environment:
    - MAIL_MAILER=log
    - DB_DATABASE=/database/database.sqlite
  volumes:
    - ~/monica/database.sqlite:/database/database.sqlite
  restart: unless-stopped
```

## Environment

- own self-hosted instance

**Comment by cellulosa** [comment]
Problem solved, I had to configure as follows:

```
monica:
  container_name: monica
  image: ghcr.io/monicahq/monica-next:main
  ports:
    - 8080:80
  environment:
    - DB_CONNECTION=sqlite
    - DB_DATABASE=/var/www/html/storage/database.sqlite
  volumes:
    - ~/monica/database.sqlite:/var/www/html/storage/database.sqlite
  restart: unless-stopped
```
