### ISSUE TITLE
When I add a new module to the template, there is no module to add

### ISSUE THREAD

**Issue by flyingnight** [monicahq/monica#7246]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/monicahq/monica/issues?q=is%3Aopen+is%3Aissue+label%3Abug) _(I've searched it)_.
- [X] I agree to follow Monica's [Code of Conduct](https://github.com/monicahq/monica/blob/main/CODE_OF_CONDUCT.md).

### Bug description

When I add a new module to the template, there is no module to add

### Steps to reproduce

settings > Personalize your account > Templates 
When I add a new module to the template, there is no module to add
![image](https://github.com/monicahq/monica/assets/63300561/f79d7a2c-5d4d-49f7-a7b1-cfe7b919e187)

### Expected behavior

How can I add this module

### Environment

Your own self-hosted instance (v5 a.k.a chandler version or main branch)

### Version of Monica

Version 5.0.0-beta.3

### Installation method

None

### Web server

None

### Database engine version

None

**Comment by rygos** [comment]
Same here. If i use chandler with internal sqlite file, everything works, if i try to install this with mariadb, there are no templates oder modules.

**Comment by TobiasAWolff** [comment]
I'm using the beta.monicahq web version also experiencing the exact same problem. Anybody also got this issue in the web version?
![Screen](https://github.com/user-attachments/assets/40497db2-d0d3-4776-a02c-1a1ab33f878e)

**Comment by Laurell876** [comment]
Tried to replicate this issue using my local instance, it seems the problem is resolved. Using MySQL for my database - if that matters.

**Comment by lenaxia** [comment]
just installed with postgres and this is not resolved.

**Comment by vnghia** [comment]
Hello all, could anyone who are using `reids` try this comment https://github.com/monicahq/monica/issues/7039#issuecomment-2699548001 ?

**Comment by zezretro** [comment]
I used the comment linked and added this extra service to my docker compose which ran the workers. I then had to reset my instance and starting fresh, but it worked

Basically, just add this to your docker compose 

```
monica-worker:
    image: ghcr.io/monicahq/monica-next:main
    container_name: monica-worker
    depends_on:
      - monica-postgres
      - monica-redis
      - monica-meilisearch
    environment:
      # copy the SAME env vars you use in the monica service
      - APP_ENV=production
      - APP_URL=${APP_URL}
      - APP_KEY=${MONICA_APP_KEY}

      - DB_CONNECTION=pgsql
      - DB_HOST=monica-postgres
      - DB_PORT=5432
      - DB_DATABASE=monica
      - DB_USERNAME=monica
      - DB_PASSWORD=${MONICA_POSTGRES_PASS}

      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=monica-redis
      - REDIS_PASSWORD=${MONICA_REDIS_PASSWORD}

      - MEILISEARCH_HOST=http://monica-meilisearch:7700
      - MEILISEARCH_KEY=${MONICA_MEILI_MASTER_KEY}

    command: >
      sh -lc "php artisan optimize:clear &&
              php artisan queue:work --queue=high,default,low --sleep=3 --tries=3 --timeout=120"
    restart: unless-stopped
```
