### ISSUE TITLE
Getting Monica instead of Chandler in docker-compose

### ISSUE THREAD

**Issue by hycday** [monicahq/monica#7333]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/monicahq/monica/issues?q=is%3Aopen+is%3Aissue+label%3Abug) _(I've searched it)_.
- [X] I agree to follow Monica's [Code of Conduct](https://github.com/monicahq/monica/blob/main/CODE_OF_CONDUCT.md).

### Bug description

Despite using the Chandler image, i still get Monica install

### Steps to reproduce

Hi all,

Here is my docker-compose.yml : 

`version: "3.3"

services:
  app:
    build: ./app
    image: ghcr.io/monicahq/monica-next:main
    env_file: .env
    volumes:
      - data:/var/www/html/storage
    restart: always
    depends_on:
      - db
      - redis

  db:
    image: mariadb:11
    env_file: .env
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
    volumes:
      - mysql:/var/lib/mysql
    restart: always

  redis:
    image: redis:alpine
    restart: always

  cron:
  cron:
    build: ./app
    image: monica-app
    command: cron.sh
    env_file: .env
    restart: always
    volumes:
      - data:/var/www/html/storage
    depends_on:
      - db
      - redis

  queue:
    build: ./app
    image: monica-app
    command: queue.sh
    env_file: .env
    restart: always
    volumes:
      - data:/var/www/html/storage
    depends_on:
      - db
      - redis

  web:
    build: ./web
    image: monica-web
    restart: always
    ports:
      - 8289:80
    volumes:
      - data:/var/www/html/storage:ro
    depends_on:
      - app

volumes:
  data:
  mysql:
`

install works well, and docker runs without any issue, however what I get is Monica Version: 4.1.2 and not Version 5.X.X 

I tried of course stopping the docker containers, removing them, removing the images and volumes, and reinstalling, didnt change anything...

Can you please guide me ? 

### Expected behavior

I am expecting to have Chandler (or Monica v 5.x.x) installed

### Environment

Your own self-hosted instance (v5 a.k.a chandler version or main branch)

### Version of Monica

4.1.2

### Installation method

Docker image

### Web server

None

### Database engine version

None

**Comment by hycday** [comment]
[Szeraax](https://github.com/Szeraax) as discussed :)

**Comment by Szeraax** [comment]
You need to use the official beta image if you wanna use the v5 branch :D You can view them all here: https://hub.docker.com/_/monica Notice the ones that are starting with 5? Those ones!

Here is my compose that I have running for this TESTING ONLY setup. I mention TESTING ONLY because I don't have any volume that I care about here. No db of any kind. And I use my env settings for the few settings there. Like so: 

```yaml
version: "3.9"
name: chandler
services:
  monica:
    container_name: monica
    image: monica:5.0.0-beta.4-apache
    environment:
      - DB_HOST=db
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - APP_ENV=production
      - APP_URL=${MY_ACCESS_URL}
      - APP_TRUSTED_PROXIES=*
      - MAIL_MAILER=log
    ports:
      - 45008:80
    restart: unless-stopped
networks: {}
```

.env file:

```
DB_USER=chandler
DB_PASS=Purplish3-Paralyze-Campsite
MY_ACCESS_URL=192.168.1.84:45008
```
