### ISSUE TITLE
VCF import is stuck or will timeout

### ISSUE THREAD

**Issue by thebino** [monicahq/monica#7390]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/monicahq/monica/issues?q=is%3Aopen+is%3Aissue+label%3Abug) _(I've searched it)_.
- [X] I agree to follow Monica's [Code of Conduct](https://github.com/monicahq/monica/blob/main/CODE_OF_CONDUCT.md).

### Bug description

I'm trying to import contacts from an vcf file (exported from google) but when I use the 'sync' option it will fail with a maximum execusion time of 30 seconds and with redis its not importing anything

### Steps to reproduce

1. Clean install
2. Setup admin user
3. start import vcf file
...

### Expected behavior

The import progress will succeed

### Environment

Your own self-hosted instance (monica v4)

### Version of Monica

4.1.2

### Installation method

Docker image

### Web server

Apache

### Database engine version

MariaDB

### Additional info

```yaml
version: "3.9"

services:
  app:
    image: monica:apache
    depends_on:
      - db
      - redis
    ports:
      - 4880:80
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=
      - APP_URL=
        # To trust all proxies that connect directly
      - APP_TRUSTED_PROXIES=*
      - DB_HOST=db
      - DB_DATABASE=monica
      - DB_USERNAME=monica
      - DB_PASSWORD=secret
      - LOG_CHANNEL=stderr
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=database
      - QUEUE_CONNECTION=redis
      - QUEUE_DRIVER=redis
      - REDIS_HOST=redis
    volumes:
      - data:/var/www/html/storage
    restart: always

  db:
    image: mariadb:11
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql
    restart: always

  redis:
    image: redis:alpine
    restart: always

volumes:
  data:
    name: monica
  mysql:
    name: mysql
```

`APP_KEY` and `APP_URL` are both set but omited for privacy.
